class Product {
  String? id; // Unique product ID (auto-generated by Firebase)
  String name; // Product name (e.g., "Air Max 90")
  String description; // Product description
  String brandId; // Reference to brand (stored as brand document ID)
  String categoryId; // Reference to category (stored as category document ID)
  double price; // Price of the shoe
  double? discountPrice; // Optional discounted price
  int stockQuantity; // Available stock
  List<String> imageUrls; // List of image URLs from Cloudinary
  List<String> sizes; // Available sizes (e.g., ["7", "8", "9"])
  // List<String> colors; // Available colors (e.g., ["Red", "Blue"])
  bool isAvailable; // Product availability status
  DateTime createdAt; // Timestamp for product creation
  DateTime updatedAt; // Timestamp for last update

  Product({
    this.id,
    required this.name,
    required this.description,
    required this.brandId,
    required this.categoryId,
    required this.price,
    this.discountPrice,
    required this.stockQuantity,
    required this.imageUrls,
    required this.sizes,
    // required this.colors,
    required this.isAvailable,
    required this.createdAt,
    required this.updatedAt,
  });

  // Convert Product to JSON for Firebase
  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'description': description,
    'brandId': brandId,
    'categoryId': categoryId,
    'price': price,
    'discountPrice': discountPrice,
    'stockQuantity': stockQuantity,
    'imageUrls': imageUrls,
    'sizes': sizes,
    // 'colors': colors,
    'isAvailable': isAvailable,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
  };

  // Create Product from JSON
  factory Product.fromJson(Map<String, dynamic> json) => Product(
    id: json['id'],
    name: json['name'],
    description: json['description'],
    brandId: json['brandId'],
    categoryId: json['categoryId'],
    price: json['price'],
    discountPrice: json['discountPrice'],
    stockQuantity: json['stockQuantity'],
    imageUrls: List<String>.from(json['imageUrls']),
    sizes: List<String>.from(json['sizes']),
    // colors: List<String>.from(json['colors']),
    isAvailable: json['isAvailable'],
    createdAt: DateTime.parse(json['createdAt']),
    updatedAt: DateTime.parse(json['updatedAt']),
  );
}
